# Generated by Django 5.2.13 on 2026-07-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otpverification',
            name='accounts_ot_user_id_e6e1a2_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sender', 'Sender / Receiver'), ('dispatcher', 'Logistics Dispatcher'), ('admin', 'Platform Admin')], db_index=True, default='sender', max_length=20, verbose_name='role'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'purpose', 'is_used', 'expires_at'], name='accounts_ot_user_id_5a5a28_idx'),
        ),
    ]
