# Generated by Django 5.2.13 on 2026-07-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_business_name_user_notify_delivery_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='territory',
            field=models.CharField(blank=True, max_length=255, verbose_name='territory'),
        ),
    ]
