# Generated by Django 5.2.13 on 2026-07-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_territory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_lga',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='delivery lga'),
        ),
        migrations.AddField(
            model_name='user',
            name='delivery_state',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='delivery state'),
        ),
    ]
