# Generated by Django 5.2.13 on 2026-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate', models.DecimalField(decimal_places=2, default=15000.0, max_digits=15)),
                ('distance_surcharge_per_km', models.DecimalField(decimal_places=2, default=45.0, max_digits=10)),
                ('express_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('same_day_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('max_cargo_weight', models.DecimalField(decimal_places=2, default=15000.0, max_digits=10)),
                ('notify_shipment_assigned', models.BooleanField(default=True)),
                ('notify_status_update', models.BooleanField(default=True)),
                ('notify_delivery_confirmed', models.BooleanField(default=True)),
                ('notify_new_request', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
