# Generated by Django 5.2.13 on 2026-07-02 11:22

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=orders.models.generate_tracking_number, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('new_request', 'New Request'), ('pending_pickup', 'Pending Pickup'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new_request', max_length=20)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_contact_name', models.CharField(max_length=255)),
                ('pickup_phone', models.CharField(max_length=20)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('pickup_notes', models.TextField(blank=True, default='')),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_name', models.CharField(max_length=255)),
                ('delivery_phone', models.CharField(max_length=20)),
                ('delivery_email', models.EmailField(blank=True, default='', max_length=254)),
                ('cargo_type', models.CharField(max_length=100)),
                ('cargo_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('cargo_value', models.DecimalField(decimal_places=2, help_text='Estimated value in Naira', max_digits=15)),
                ('cargo_priority', models.CharField(choices=[('standard', 'Standard'), ('express', 'Express')], default='standard', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('distance_surcharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_orders', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
