# Generated by Django 5.2.13 on 2026-07-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status_alter_orderstatushistory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='driver',
            name='trips_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, help_text='Long-term assigned driver for fleet overview.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='orders.driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='capacity_tonnes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='health_percentage',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
