# Generated by Django 5.2.13 on 2026-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_driver_created_at_driver_driver_id_driver_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='roadworthy_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('on_duty', 'On Duty'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
