# Generated by Django 5.2.13 on 2026-07-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_vehicle_insurance_expiry_vehicle_make_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['registration_number']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new_request', 'New Request'), ('assigned', 'Assigned'), ('pending_pickup', 'Pending Pickup'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='new_request', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
