# Generated by Django 5.2.13 on 2026-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_driver_options_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='display_name',
            field=models.CharField(blank=True, help_text="Human-readable event title shown in the shipment timeline UI, e.g. 'Driver & Vehicle Assigned', 'Pickup Confirmed'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='description',
            field=models.CharField(blank=True, help_text='Contextual subtitle for the event, e.g. actor name, location, or note.', max_length=255),
        ),
    ]
