# Generated by Django 5.2.13 on 2026-07-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderstatushistory_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='True once the recipient (the other party in the 2-person chat) has read this message.'),
        ),
    ]
