# Generated by Django 5.2.13 on 2026-07-25 08:00

import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_pin',
            field=models.CharField(default=orders.models.generate_delivery_pin, help_text='PIN required to confirm delivery', max_length=10),
        ),
    ]
