# Generated by Django 5.2.13 on 2026-07-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_delivery_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cargo_priority',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('same_day', 'Same Day')], default='standard', max_length=20),
        ),
    ]
